### ISSUE TITLE
Oops, an error occurred! $className must be a non empty string.

### ISSUE THREAD

**Issue by helmut-winkelbach** [bitmotion/static-info-tables-fa#2]
Dear Florian,
on TYPO3 9.5.5 i did install static-info-tables 6.7.4 without problem
and static-info-tables-fa 6.7.3, here i get on Listview the error.

I did database update and deleted cache.

**Comment by bmheins** [comment]
Dear Helmut,

I cannot reproduce your problem on a freshly installed TYPO3 9.5.5. Can you give me some more information on the issue, i.e. how to reproduce the error?

Best regards,
Olli
